// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCreateOutcomeBatch implements pgx.CopyFromSource.
type iteratorForCreateOutcomeBatch struct {
	rows                 []CreateOutcomeBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateOutcomeBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateOutcomeBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].MarketID,
		r.rows[0].Label,
		r.rows[0].Index,
		r.rows[0].IsWinner,
	}, nil
}

func (r iteratorForCreateOutcomeBatch) Err() error {
	return nil
}

func (q *Queries) CreateOutcomeBatch(ctx context.Context, arg []CreateOutcomeBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"outcomes"}, []string{"id", "market_id", "label", "index", "is_winner"}, &iteratorForCreateOutcomeBatch{rows: arg})
}
