// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarkets = `-- name: CountMarkets :one
SELECT COUNT(*) FROM markets
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR category = $2)
`

type CountMarketsParams struct {
	Status   pgtype.Text
	Category pgtype.Text
}

func (q *Queries) CountMarkets(ctx context.Context, arg CountMarketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMarkets, arg.Status, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMarket = `-- name: CreateMarket :exec
INSERT INTO markets (id, title, description, category, market_type, status,
    created_by, resolved_outcome_id, created_at, updated_at, end_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateMarketParams struct {
	ID                string
	Title             string
	Description       string
	Category          string
	MarketType        string
	Status            string
	CreatedBy         string
	ResolvedOutcomeID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	EndTime           pgtype.Timestamptz
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) error {
	_, err := q.db.Exec(ctx, createMarket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.MarketType,
		arg.Status,
		arg.CreatedBy,
		arg.ResolvedOutcomeID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EndTime,
	)
	return err
}

const getMarketByID = `-- name: GetMarketByID :one
SELECT id, title, description, category, market_type, status,
       created_by, resolved_outcome_id, created_at, updated_at, end_time
FROM markets
WHERE id = $1
`

type GetMarketByIDRow struct {
	ID                string
	Title             string
	Description       string
	Category          string
	MarketType        string
	Status            string
	CreatedBy         string
	ResolvedOutcomeID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	EndTime           pgtype.Timestamptz
}

func (q *Queries) GetMarketByID(ctx context.Context, id string) (GetMarketByIDRow, error) {
	row := q.db.QueryRow(ctx, getMarketByID, id)
	var i GetMarketByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.MarketType,
		&i.Status,
		&i.CreatedBy,
		&i.ResolvedOutcomeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndTime,
	)
	return i, err
}

const listMarkets = `-- name: ListMarkets :many
SELECT id, title, description, category, market_type, status,
       created_by, resolved_outcome_id, created_at, updated_at, end_time
FROM markets
WHERE ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR category = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMarketsParams struct {
	Limit    int32
	Offset   int32
	Status   pgtype.Text
	Category pgtype.Text
}

type ListMarketsRow struct {
	ID                string
	Title             string
	Description       string
	Category          string
	MarketType        string
	Status            string
	CreatedBy         string
	ResolvedOutcomeID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	EndTime           pgtype.Timestamptz
}

func (q *Queries) ListMarkets(ctx context.Context, arg ListMarketsParams) ([]ListMarketsRow, error) {
	rows, err := q.db.Query(ctx, listMarkets,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsRow{}
	for rows.Next() {
		var i ListMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.MarketType,
			&i.Status,
			&i.CreatedBy,
			&i.ResolvedOutcomeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarket = `-- name: UpdateMarket :execrows
UPDATE markets SET
    title = $1, description = $2, category = $3, market_type = $4, status = $5,
    created_by = $6, resolved_outcome_id = $7, updated_at = $8, end_time = $9
WHERE id = $10
`

type UpdateMarketParams struct {
	Title             string
	Description       string
	Category          string
	MarketType        string
	Status            string
	CreatedBy         string
	ResolvedOutcomeID pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	EndTime           pgtype.Timestamptz
	ID                string
}

func (q *Queries) UpdateMarket(ctx context.Context, arg UpdateMarketParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMarket,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.MarketType,
		arg.Status,
		arg.CreatedBy,
		arg.ResolvedOutcomeID,
		arg.UpdatedAt,
		arg.EndTime,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
