// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mint_transactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createMintTransaction = `-- name: CreateMintTransaction :exec
INSERT INTO mint_transactions (id, user_id, market_id, quantity, cost, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMintTransactionParams struct {
	ID        string
	UserID    string
	MarketID  string
	Quantity  decimal.Decimal
	Cost      decimal.Decimal
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateMintTransaction(ctx context.Context, arg CreateMintTransactionParams) error {
	_, err := q.db.Exec(ctx, createMintTransaction,
		arg.ID,
		arg.UserID,
		arg.MarketID,
		arg.Quantity,
		arg.Cost,
		arg.CreatedAt,
	)
	return err
}
