// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type ApiKey struct {
	ID        string
	UserID    string
	KeyHash   string
	KeyPrefix string
	Label     string
	IsActive  bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Market struct {
	ID                string
	Title             string
	Description       string
	MarketType        string
	Category          string
	Status            string
	CreatedBy         string
	EndTime           pgtype.Timestamptz
	ResolvedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ResolvedOutcomeID pgtype.UUID
}

type MintTransaction struct {
	ID        string
	UserID    string
	MarketID  string
	Quantity  decimal.Decimal
	Cost      decimal.Decimal
	CreatedAt pgtype.Timestamptz
}

type Order struct {
	ID             string
	UserID         string
	MarketID       string
	OutcomeID      string
	Side           string
	Price          decimal.Decimal
	Quantity       decimal.Decimal
	FilledQuantity decimal.Decimal
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Outcome struct {
	ID       string
	MarketID string
	Label    string
	Index    int32
	IsWinner bool
}

type Position struct {
	ID        string
	UserID    string
	MarketID  string
	OutcomeID string
	Quantity  decimal.Decimal
	AvgPrice  decimal.Decimal
	UpdatedAt pgtype.Timestamptz
}

type Trade struct {
	ID           string
	MarketID     string
	OutcomeID    string
	MakerOrderID string
	TakerOrderID string
	MakerUserID  string
	TakerUserID  string
	Price        decimal.Decimal
	Quantity     decimal.Decimal
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID            string
	WalletAddress pgtype.Text
	UserType      string
	Balance       decimal.Decimal
	LockedBalance decimal.Decimal
	IsAdmin       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserRanking struct {
	UserID        string
	WalletAddress pgtype.Text
	UserType      string
	TotalAssets   int32
	Pnl           int32
	Volume        int64
	WinRate       interface{}
	UpdatedAt     interface{}
}
