// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cancelAllOrdersByMarket = `-- name: CancelAllOrdersByMarket :execrows
UPDATE orders SET status = 'cancelled', updated_at = NOW()
WHERE market_id = $1 AND status IN ('open', 'partially_filled')
`

func (q *Queries) CancelAllOrdersByMarket(ctx context.Context, marketID string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelAllOrdersByMarket, marketID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) FROM orders WHERE user_id = $1
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, user_id, market_id, outcome_id, side, price, quantity,
    filled_quantity, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateOrderParams struct {
	ID             string
	UserID         string
	MarketID       string
	OutcomeID      string
	Side           string
	Price          decimal.Decimal
	Quantity       decimal.Decimal
	FilledQuantity decimal.Decimal
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.MarketID,
		arg.OutcomeID,
		arg.Side,
		arg.Price,
		arg.Quantity,
		arg.FilledQuantity,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, market_id, outcome_id, side, price, quantity,
       filled_quantity, status, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MarketID,
		&i.OutcomeID,
		&i.Side,
		&i.Price,
		&i.Quantity,
		&i.FilledQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllOpenOrders = `-- name: ListAllOpenOrders :many
SELECT id, user_id, market_id, outcome_id, side, price, quantity,
       filled_quantity, status, created_at, updated_at
FROM orders
WHERE status IN ('open', 'partially_filled')
ORDER BY market_id, outcome_id, created_at ASC
`

func (q *Queries) ListAllOpenOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAllOpenOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Side,
			&i.Price,
			&i.Quantity,
			&i.FilledQuantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenOrdersByMarket = `-- name: ListOpenOrdersByMarket :many
SELECT id, user_id, market_id, outcome_id, side, price, quantity,
       filled_quantity, status, created_at, updated_at
FROM orders
WHERE market_id = $1 AND status IN ('open', 'partially_filled')
ORDER BY price DESC, created_at ASC
`

func (q *Queries) ListOpenOrdersByMarket(ctx context.Context, marketID string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOpenOrdersByMarket, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Side,
			&i.Price,
			&i.Quantity,
			&i.FilledQuantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, market_id, outcome_id, side, price, quantity,
       filled_quantity, status, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID string
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Side,
			&i.Price,
			&i.Quantity,
			&i.FilledQuantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE orders SET status = $1, filled_quantity = $2, updated_at = NOW() WHERE id = $3
`

type UpdateOrderStatusParams struct {
	Status         string
	FilledQuantity decimal.Decimal
	ID             string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.FilledQuantity, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
