// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outcomes.sql

package sqlcgen

import (
	"context"
)

type CreateOutcomeBatchParams struct {
	ID       string
	MarketID string
	Label    string
	Index    int32
	IsWinner bool
}

const listOutcomesByMarket = `-- name: ListOutcomesByMarket :many
SELECT id, market_id, label, index, is_winner
FROM outcomes
WHERE market_id = $1
ORDER BY index ASC
`

func (q *Queries) ListOutcomesByMarket(ctx context.Context, marketID string) ([]Outcome, error) {
	rows, err := q.db.Query(ctx, listOutcomesByMarket, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outcome{}
	for rows.Next() {
		var i Outcome
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Label,
			&i.Index,
			&i.IsWinner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOutcomeWinner = `-- name: SetOutcomeWinner :execrows
UPDATE outcomes SET is_winner = true WHERE id = $1
`

func (q *Queries) SetOutcomeWinner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, setOutcomeWinner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
