// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getPositionByUserAndOutcome = `-- name: GetPositionByUserAndOutcome :one
SELECT id, user_id, market_id, outcome_id, quantity, avg_price, updated_at
FROM positions
WHERE user_id = $1 AND outcome_id = $2
`

type GetPositionByUserAndOutcomeParams struct {
	UserID    string
	OutcomeID string
}

func (q *Queries) GetPositionByUserAndOutcome(ctx context.Context, arg GetPositionByUserAndOutcomeParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByUserAndOutcome, arg.UserID, arg.OutcomeID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MarketID,
		&i.OutcomeID,
		&i.Quantity,
		&i.AvgPrice,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositionsByMarket = `-- name: ListPositionsByMarket :many
SELECT id, user_id, market_id, outcome_id, quantity, avg_price, updated_at
FROM positions
WHERE market_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListPositionsByMarket(ctx context.Context, marketID string) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByMarket, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Quantity,
			&i.AvgPrice,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByUser = `-- name: ListPositionsByUser :many
SELECT id, user_id, market_id, outcome_id, quantity, avg_price, updated_at
FROM positions
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListPositionsByUser(ctx context.Context, userID string) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Quantity,
			&i.AvgPrice,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (id, user_id, market_id, outcome_id, quantity, avg_price, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, market_id, outcome_id) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    avg_price = EXCLUDED.avg_price,
    updated_at = EXCLUDED.updated_at
`

type UpsertPositionParams struct {
	ID        string
	UserID    string
	MarketID  string
	OutcomeID string
	Quantity  decimal.Decimal
	AvgPrice  decimal.Decimal
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.Exec(ctx, upsertPosition,
		arg.ID,
		arg.UserID,
		arg.MarketID,
		arg.OutcomeID,
		arg.Quantity,
		arg.AvgPrice,
		arg.UpdatedAt,
	)
	return err
}
