// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countTradesByMarket = `-- name: CountTradesByMarket :one
SELECT COUNT(*) FROM trades WHERE market_id = $1
`

func (q *Queries) CountTradesByMarket(ctx context.Context, marketID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTradesByMarket, marketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTradesByUser = `-- name: CountTradesByUser :one
SELECT COUNT(*) FROM trades WHERE maker_user_id = $1 OR taker_user_id = $1
`

func (q *Queries) CountTradesByUser(ctx context.Context, makerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTradesByUser, makerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrade = `-- name: CreateTrade :exec
INSERT INTO trades (id, market_id, outcome_id, maker_order_id, taker_order_id,
    maker_user_id, taker_user_id, price, quantity, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateTradeParams struct {
	ID           string
	MarketID     string
	OutcomeID    string
	MakerOrderID string
	TakerOrderID string
	MakerUserID  string
	TakerUserID  string
	Price        decimal.Decimal
	Quantity     decimal.Decimal
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) error {
	_, err := q.db.Exec(ctx, createTrade,
		arg.ID,
		arg.MarketID,
		arg.OutcomeID,
		arg.MakerOrderID,
		arg.TakerOrderID,
		arg.MakerUserID,
		arg.TakerUserID,
		arg.Price,
		arg.Quantity,
		arg.CreatedAt,
	)
	return err
}

const listTradesByMarket = `-- name: ListTradesByMarket :many
SELECT id, market_id, outcome_id, maker_order_id, taker_order_id,
       maker_user_id, taker_user_id, price, quantity, created_at
FROM trades
WHERE market_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTradesByMarketParams struct {
	MarketID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListTradesByMarket(ctx context.Context, arg ListTradesByMarketParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTradesByMarket, arg.MarketID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.OutcomeID,
			&i.MakerOrderID,
			&i.TakerOrderID,
			&i.MakerUserID,
			&i.TakerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesByUser = `-- name: ListTradesByUser :many
SELECT id, market_id, outcome_id, maker_order_id, taker_order_id,
       maker_user_id, taker_user_id, price, quantity, created_at
FROM trades
WHERE maker_user_id = $1 OR taker_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTradesByUserParams struct {
	MakerUserID string
	Limit       int32
	Offset      int32
}

func (q *Queries) ListTradesByUser(ctx context.Context, arg ListTradesByUserParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTradesByUser, arg.MakerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.OutcomeID,
			&i.MakerOrderID,
			&i.TakerOrderID,
			&i.MakerUserID,
			&i.TakerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
