// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1::text IS NULL OR user_type = $1)
  AND ($2::boolean IS NULL OR is_admin = $2)
`

type CountUsersParams struct {
	UserType pgtype.Text
	IsAdmin  pgtype.Bool
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.UserType, arg.IsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, wallet_address, user_type, balance, locked_balance, is_admin, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserParams struct {
	ID            string
	WalletAddress pgtype.Text
	UserType      string
	Balance       decimal.Decimal
	LockedBalance decimal.Decimal
	IsAdmin       bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.WalletAddress,
		arg.UserType,
		arg.Balance,
		arg.LockedBalance,
		arg.IsAdmin,
		arg.CreatedAt,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, wallet_address, user_type, balance, locked_balance, is_admin, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            string
	WalletAddress pgtype.Text
	UserType      string
	Balance       decimal.Decimal
	LockedBalance decimal.Decimal
	IsAdmin       bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.UserType,
		&i.Balance,
		&i.LockedBalance,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByWallet = `-- name: GetUserByWallet :one
SELECT id, wallet_address, user_type, balance, locked_balance, is_admin, created_at
FROM users
WHERE wallet_address = $1
`

type GetUserByWalletRow struct {
	ID            string
	WalletAddress pgtype.Text
	UserType      string
	Balance       decimal.Decimal
	LockedBalance decimal.Decimal
	IsAdmin       bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUserByWallet(ctx context.Context, walletAddress pgtype.Text) (GetUserByWalletRow, error) {
	row := q.db.QueryRow(ctx, getUserByWallet, walletAddress)
	var i GetUserByWalletRow
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.UserType,
		&i.Balance,
		&i.LockedBalance,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, wallet_address, user_type, balance, locked_balance, is_admin, created_at
FROM users
WHERE ($3::text IS NULL OR user_type = $3)
  AND ($4::boolean IS NULL OR is_admin = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit    int32
	Offset   int32
	UserType pgtype.Text
	IsAdmin  pgtype.Bool
}

type ListUsersRow struct {
	ID            string
	WalletAddress pgtype.Text
	UserType      string
	Balance       decimal.Decimal
	LockedBalance decimal.Decimal
	IsAdmin       bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.UserType,
		arg.IsAdmin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletAddress,
			&i.UserType,
			&i.Balance,
			&i.LockedBalance,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserBalance = `-- name: UpdateUserBalance :execrows
UPDATE users SET balance = $1, locked_balance = $2 WHERE id = $3
`

type UpdateUserBalanceParams struct {
	Balance       decimal.Decimal
	LockedBalance decimal.Decimal
	ID            string
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserBalance, arg.Balance, arg.LockedBalance, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
